name: 'Find new CVEs'
description: |
  Check if there is a new CVE for each dependency

inputs:
  webhook-url:
    description: Slack Webhook URL
    required: true

outputs:
  new-cves:
    description: If there is a new CVE or not
    value: ${{ steps.find-new-cves.outputs.new-cves }}

runs:
  using: 'composite'
  steps:
    - id: find-new-cves
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        cd "${{ github.action_path }}/entrypoint"

        go build -o ./entrypoint

        new_cves="$(./entrypoint \
          --json-filepath "${{ github.workspace }}/artifacts/cves.json"
          --webhook-url "${{ inputs.webhook-url }}" \
          --dep-list "${{ github.workspace }}/cve-notification-app/dependencies.csv"
        )"

        echo "::set-output name=new-cves::"${new_cves}""

        rm -f ./entrypoint