name: 'Generate the JSON file with all the CVEs recorded until now'
description: |
  Generate the JSON file with all the CVEs recorded until now

runs:
  using: 'composite'
  steps:
    - id: generate-actual-cve-list
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        cd "${{ github.action_path }}/entrypoint"

        go build -o ./entrypoint

        ./entrypoint \
          --json-filepath "${{ github.workspace }}/artifacts/cves.json" \
          --dep-list "${{ github.workspace }}/cve-notification-app/dependencies.csv"

        rm -f ./entrypoint