name: Main

on:
  workflow_dispatch: { }
  schedule:
    - cron: '0 1 */1 * *'
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Run tests
        run: |
          bundle exec rspec